QUESTION_TYPES_DROP_DOWN = 'drop_down'
QUESTION_TYPES_TEXT_FIELD = 'text_field'
QUESTION_TYPES_TEXT_AREA = 'text_area'

QUESTION_TYPES = (
    QUESTION_TYPES_DROP_DOWN,
    QUESTION_TYPES_TEXT_FIELD,
    QUESTION_TYPES_TEXT_AREA
)

# ######################################################

VALIDATIONS_REQUIRED = 'required'
VALIDATIONS_IS_STRING = 'is_string'
VALIDATIONS_IS_DECIMAL = 'is_decimal'

VALIDATIONS = (
    VALIDATIONS_REQUIRED,
    VALIDATIONS_IS_STRING,
    VALIDATIONS_IS_DECIMAL
)

# ######################################################

CONDITIONS_ANY = 'any'
CONDITIONS_EQUAL = 'equal'
CONDITIONS_GTE = 'gte'

CONDITIONS = (
    CONDITIONS_ANY,
    CONDITIONS_EQUAL,
    CONDITIONS_GTE
)
